# mem4_game/Makefile.toml
# Workspace with members

[config]
skip_core_tasks = true

#region: public callable tasks/flows
[tasks.default]
description = "show list of callable public tasks"
clear = true
command = "cargo"
args = ["make","--list-all-steps"]

[tasks.dev]
description = "cargo make dev for every workspace member"
workspace = true
command = "cargo"
args = ["make","dev"]

[tasks.release]
description = "cargo make release for every workspace member"
workspace = true
command = "cargo"
args = ["make","release"]

[tasks.doc]
description = "cargo make doc for every workspace member"
workspace = true
clear=true
dependencies = [
    "insert-readme",
    "cargo-doc",
]

[tasks.publish]
description = "TODO: copy the content of /mem4_game/webfolder/mem4/ to google vm. How?? ssh ?"
workspace = true
command="cargo"
args=["make", "publish"]

#endregion

[tasks.insert-readme]
clear = true
private = true
description = "copy the content of readme.md into *.rs comments (for the docs)"
script= ["..\\..\\utils\\lmake_readme.exe"]

[tasks.cargo-doc]
clear = true
private = true
description = "call cargo doc"
command="cargo"
args=["doc","--no-deps","--document-private-items","--open"]
