[tasks.init]
disabled = true

#I tried with windows-alias here, but it didn't work.

[tasks.end]
script = [
    "xcopy c:\\Users\\Luciano\\RustProjects\\mem4_game\\mem4\\pkg\\*.* c:\\Users\\Luciano\\RustProjects\\mem4_game\\webfolder\\mem4\\pkg\\ /y ",
    "xcopy c:\\Users\\Luciano\\RustProjects\\mem4_game\\target\\debug\\mem4_server.exe c:\\Users\\Luciano\\RustProjects\\mem4_game\\webfolder\\ /y ",
# I cannot script the exact IP here.  
# It must be copied from the mem4_server.exe output.
    "start chrome http://127.0.0.22:80", 
    "start chrome http://127.0.0.22:80", 
    "cd webfolder",
    "mem4_server.exe"
]
