# mem4_game/mem4_common/Makefile.toml
#https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: public callable tasks/flows

    [tasks.default]
    description = "show list of public callable tasks"
    clear = true
    command = "cargo"
    args = ["make","--list-all-steps"]

    [tasks.dev]
    description = "cargo build development"
    clear=true
    dependencies = ["build-dev"]

    [tasks.release]
    description = "cargo build release"
    clear=true
    dependencies = ["build-release"]

    [tasks.doc]
    description="call cargo doc"
    clear=true
    command="cargo"
    args=["doc","--no-deps","--open"]

#endregion


[tasks.build-dev]
clear=true
private=true
command = "cargo"
args = ["build"]

[tasks.build-release]
clear=true
private=true
command = "cargo"
args = ["build","--release"]
