#https://github.com/sagiegurari/cargo-make/blob/master/src/lib/Makefile.stable.toml

[config]
skip_core_tasks = true

#region: flows
[tasks.default]
dependencies = [
    "build",
    "post-build",
]

[tasks.release]
dependencies = [
    "build-release",
    "post-build",
]
#endregion

[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web"]

[tasks.build-release]
command = "wasm-pack"
args = ["build","--target", "web"]

[tasks.post-build]
linux_alias = "linux_post-build"
windows_alias = "windows_post-build"

[tasks.linux_post-build]
script = [
    "\\cp ~/rustprojects/mem4_game/mem4/pkg/* -rf -v ~/rustprojects/mem4_game/webfolder/mem4/pkg",
]

[tasks.windows_post-build]
script = [
    "xcopy c:\\Users\\Luciano\\rustprojects\\mem4_game\\mem4\\pkg\\*.* c:\\Users\\Luciano\\rustprojects\\mem4_game\\webfolder\\mem4\\pkg\\ /y ",
]
