
[tasks.init]
disabled = true

[tasks.build]
command = "wasm-pack"
args = ["build", "--target", "web"]


[tasks.pre-format]
disabled = true

[tasks.format]
disabled = true

[tasks.post-format]
disabled = true

[tasks.format-flow]
disabled = true

[tasks.post-build]
disabled = true

[tasks.pre-test]
disabled = true

[tasks.test]
disabled = true

[tasks.post-test]
disabled = true

[tasks.test-flow]
disabled = true

[tasks.pre-build]
disabled = true

[tasks.end]
disabled = true